spring:
  application:
    name: todo-list-graphql
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: test
    password: test
  h2:
    console.enabled: true

  graphql:
    graphiql.enabled: true